name: Scrape ForexFactory Daily

on:
  schedule:
    - cron: "0 0 * * 1-5"  # 🕛 A las 00:00 UTC de lunes (1) a viernes (5)
  workflow_dispatch:  # También lo podés disparar manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python news-bot-eurusd.py
